FROM openjdk
WORKDIR usr/src
ADD ./target/WalletServiceApplication-0.0.1-SNAPSHOT.jar usr/src/WalletServiceApplication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "usr/src/WalletServiceApplication-0.0.1-SNAPSHOT.jar"]