FROM openjdk
WORKDIR usr/src
ADD ./target/UserServiceApplication-0.0.1-SNAPSHOT.jar usr/src/UserServiceApplication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "usr/src/UserServiceApplication-0.0.1-SNAPSHOT.jar"]